### ISSUE TITLE
Migrations Path hard-coded when ActiveRecord already stores it

### ISSUE THREAD

**Issue by HoneyryderChuck** [bmizerany/sinatra-activerecord#11]
Hi,

I've noticed that in the ActiveRecordTasks you have a method migrations_dir which basically returns "db/migrate". Well, Actually one can define the migrations paths directly using ActiveRecord::Migrator.migrations_paths. Why can't this be used? If I want to place the migrations somewhere else, it doesn't leave me much of a choice, does it?

**Comment by janko** [comment]
You meant to post this on [janko-m/sinatra-activerecord](https://github.com/janko-m/sinatra-activerecord), right?

**Comment by HoneyryderChuck** [comment]
yup

**Comment by janko** [comment]
https://github.com/janko-m/sinatra-activerecord/blob/master/CHANGELOG.md#version-120

:)

**Comment by HoneyryderChuck** [comment]
nice :)
