### ISSUE TITLE
rake aborted! message for sinatra-activerecord

### ISSUE THREAD

**Issue by UzmaKR** [bmizerany/sinatra-activerecord#13]
Here is my error message when I run 'bundle exec rake -T' :
  rake aborted!
  cannot load such file -- sinatra-activerecord

My Gemfile:
  source "https://rubygems.org"
  gem "sinatra"
  gem "sqlite3"
  gem "activerecord"
  gem "sinatra-activerecord", "~> 1.4.0"
  gem "rake"
  gem "thin"

My Rakefile:
  require "./app"
  require "sinatra/activerecord/rake"

My app.rb:
  require "sinatra"
  require "active_record"
  require "sinatra-activerecord"  (<== aborts here...)

Doing 'bundle show' shows this:
  Gems included by the bundle:
  .......
- sinatra-activerecord (1.4.0)

Do you have any suggestions ? I don't know why I am getting this error.

Thanks.
Uzma

**Comment by UzmaKR** [comment]
OK. I resolved the issue. Maybe this solution will help other folks.
My Rakefile remains the same. 
In app.rb:
  require "sinatra"
  require "active_record"
  require "sinatra/activerecord"

So, substituting 'sinatra-activerecord' with 'sinatra/activerecord' made the 'rake' command run.

Regards.

**Comment by janko** [comment]
It's written in the [readme](https://github.com/janko-m/sinatra-activerecord#setup) (the gem moved to my fork).

**Comment by UzmaKR** [comment]
Thanks.
