### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base on rake db:seed

### ISSUE THREAD

**Issue by SauloSilva** [bmizerany/sinatra-activerecord#14]
I'm using this gem in the latest version , configured like this in the documentation. `db:migrate`, `db:create`, `db:purge`, `db:reset`, `db:drop` all worked less `db:seed`.

When running a task , it triggers a connection error with the bd:

```
ActiveRecord :: ConnectionNotEstablished : Em pool de conexão é ActiveRecord :: Base
```

I checked and found a solution to this problem, which was load_config carrier to the task of seeds this:

``` ruby
task seed: : load_config
```

I am available to help with this problem.

**Comment by janko** [comment]
What version of ActiveRecord are you using? Did you remember to run prepend the Rake comand with `bundle exec`?

**Comment by SauloSilva** [comment]
**ActiveRecord 4.2.0**

`bundle exec rake db:seed` still continues with the same error.

![image](http://i.imgur.com/qIbeZgN.png)

**Comment by janko** [comment]
I only now realized that this isn't the right repo :). Blake Mizerany and I agreed that I will make a fork ([janko-m/sinatra-activerecord](https://github.com/janko-m/sinatra-activerecord)), so that is now the official repo.

One more question, did you forget to `require "./app"` in your Rakefile (or whatever your main Sinatra file is)? If you didn't forget, reraise the issue on my repo and we'll continue the discussion there.

**Comment by SauloSilva** [comment]
@janko-m I did not forget to make the require of app.js , I did it in my **Rakefile**:

``` ruby
require 'sinatra/activerecord/rake'

namespace :db do
  task :load_config do
    require File.expand_path('../app', __FILE__)
  end
end
```

For the `rake db:seed` task work needed to add these lines.

``` ruby
require 'sinatra/activerecord/rake'

namespace :db do
  task :load_config do
    require File.expand_path('../app', __FILE__)
  end

  # added these lines to work
  task seed: :load_config do
  end
end
```

But I think these lines should be added within the gem.

Thanks @janko-m.

**Comment by janko** [comment]
Wow, you're totally right, this is much better than requiring the app at the top level. This way the app won't have to be loaded on every Rake task, just on the ActiveRecord ones.

I [fixed `db:seed`](https://github.com/janko-m/sinatra-activerecord/commit/cad623ae40796bbebafffbb31a1a12a5964cc354) like you suggested, and released a new version. I also updated the readme suggesting your way.

**Comment by SauloSilva** [comment]
Wow, perfect, thanks for helpfulness. Updated the gem with the new version and now is working perfectly.
Thanks @janko-m 

I'm closing this issue.
